### ISSUE TITLE
TLS EC is failing on EKS

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#100]
@ayasuda2OO3 We are currently seeing the TLS EC  app is not getting sync on Argocd with below error. As suggested yesterday I have rollback the changes to last successful code but still the error remains the same.

Deployment in version "v1" cannot be handled as a Deployment: v1.Deployment.Spec: v1.DeploymentSpec.Template: v1.PodTemplateSpec.Spec: v1.PodSpec.Containers: []v1.Container: v1.Container.Env: []v1.EnvVar: v1.EnvVar.Value: ReadString: expects " or n, but found t, error found in #10 byte of ...|,"value":true}],"ima|..., bigger context ...|.lpt","value":"7980"},{"name":"conf.rpt","value":true}],"image":"enterprisecon

Please check.

**Comment by simran3695** [comment]
After looking on the error i got https://stackoverflow.com/questions/59354115/helm-upgrade-fails-with-error-expects-or-n-but-found-t and I tried to add quotes to rpt, plugin.port and plg in quotes and now the app is atleast getting sync.

The pod is failing now with different error.

[EC Server] 2020/10/09 10:31:18 [cleaned up logging file(s). connectivity.log plugin.log]
 [EC Server] 2020/10/09 10:31:18 [Rev: v1.hokkaido.212]
 [EC Agent] main pacakge exception: interface conversion: interface {} is *string, not *bo
ol

**Comment by ayasuda2OO3** [comment]
@simran3695 please confirm the fix and close.

**Comment by ayasuda2OO3** [comment]
#113 #112 #110 #109 #108 #106 #105 #104 #103

**Comment by simran3695** [comment]
TLS EC is now fixed. Hence closing this issue. Thankyou for the the help and guidance to fix this as always.
