### ISSUE TITLE
Run EC container as non-root("ec") user

### ISSUE THREAD

**Issue by palokam** [EC-Release/oci#111]
EC Agent container is running as a root, but for security reasons, we should run this as non-root user (ec user)

Please create a user called "ec" and use to that user to run in the container

**Comment by ayasuda2OO3** [comment]
pod owner/configurator has the role and say in how the container should be deployed. Adding k8s spec in example to run a container as a non-root user. @palokam @simran3695

**Comment by ayasuda2OO3** [comment]
The [example output](https://travis-ci.com/github/EC-Release/oci/jobs/399786120#L2506) the spec w/ a non-root user with uid#4000, resulting in the non-privileged deployment with restrictions such as the inaccessibility to any ports num < 1024. The controller of the pod may create an user (ec) in its the OCI spec mapping to the non-privileged container (agent+plugin) E.g. UID: 4000 -> ec.

**Comment by palokam** [comment]
CI Output does not show that that container running as a user as 4000 UID. 

Can you verify in the logs that ecagent is running as UID 4000?
```
No resources found in default namespace.

Error from server (NotFound): deployments.apps "example-1602706282-agent-plg-58bc89ffcd-5qrxt" not found

*** done debug go ahead delete all.

**Comment by ayasuda2OO3** [comment]
add argocd to [pkg deployment simulation](https://github.com/EC-Release/oci/blob/v1.1beta_helm_pkg_update_multi_contnr/script.sh#L75) as specified to avoid discrepancy. @palokam @sheshankgujjari @simran3695

**Comment by ayasuda2OO3** [comment]
add argocd to [pkg deployment simulation](https://github.com/EC-Release/oci/blob/v1.1beta_helm_pkg_update_multi_contnr/argocd-deployment-sim.sh) as specified to avoid discrepancy. @palokam @sheshankgujjari @simran3695

**Comment by ayasuda2OO3** [comment]
@naddym please confirm [this securityContext setting](https://github.com/EC-Release/oci/blob/v1.1beta_helm_pkg_update_multi_contnr/k8s/example/values.yaml#L131) will fix the permission issue.

The agt+plugin container will remain the current user context and running as a non-privileged user at cluster. @palokam @simran3695
