### ISSUE TITLE
EC Image pull request limit

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#124]
@ayasuda-ge We are currently seeing issue on EKS EC's where the pull image is not working because of its per day pull rate limit. When this happens we see outage on TC environment too because some VLAN EC wich is tied with TC STS goes down completely. Please provide a fix for this issue.

**Comment by ayasuda-ge** [comment]
Acknowledged. Solution in progress.

**Comment by ayasuda-ge** [comment]
General update. PR #125 still in progress. @sheshankgujjari @simran3695
