### ISSUE TITLE
Issue installing helm without notes.tct file in the template.

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#14]
We are getting below issue while installing helm without notes.txt.

 helm install --dry-run /Users/sheshankgujjari/Downloads/agent+helper-0.1.0.tgz --generate-name --namespace ec-test

Error: library charts are not installable.

Can you please help here.

**Comment by ayasuda2OO3** [comment]
```agent-helper``` is a chart library, users should consider using agent and update it in the dependency. Moreover, it seems you are trying to download the package manually, this may create a maintenance burden in your environment. The Helm official suggests using its helm package manager as the best practice. Please follow [the instruction](https://github.com/Enterprise-connect/oci/tree/v1.1beta/k8s#add-dependency-repo) 

Thanks for the feedback.

**Comment by ayasuda2OO3** [comment]
close for merged PRs #15 #12
