### ISSUE TITLE
Liveness probe issue 

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#16]
We have successfully created pods but now we are getting below error when we run "kubectl describe pod -n ec-engineering" where ec-engineering is our namespace in CI cluster.

![image](https://user-images.githubusercontent.com/65241877/84158027-06d3b280-aa89-11ea-9e14-a2e26a9d1e45.png)

Just for your info we have used nginx ingress here.

ingress:
  enabled: true
  annotations:
     kubernetes.io/ingress.class: nginx
     #kubernetes.io/tls-acme: "true"
  hosts:
    - host: ec-eng-ci-dc-aws.apps.ge.com
      paths: []

**Comment by ayasuda2OO3** [comment]
The agent in the pod apparently failed at launch.

Can you clarify the following-

1) can you provide the pod log?
2) a print out of the env in this pod? 
3) did you follow the instruction [to generate the env vars for the deployment?](https://github.com/Enterprise-connect/oci/tree/v1.1beta/k8s#agentchart-configuration-conversion) @simran3695

**Comment by sheshankgujjari** [comment]
kubectl get po ec-eng-ci-agent-59dfb68949-n2nh9 -n ec-engineering -o yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: "2020-06-09T13:46:41Z"
  generateName: ec-eng-ci-agent-59dfb68949-
  labels:
    app.kubernetes.io/instance: ec-eng-ci
    app.kubernetes.io/name: agent
    pod-template-hash: 59dfb68949
  name: ec-eng-ci-agent-59dfb68949-n2nh9
  namespace: ec-engineering
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: ec-eng-ci-agent-59dfb68949
    uid: ef37d8ab-3c1f-428d-bcf7-98e662af82be
  resourceVersion: "5575929"
  selfLink: /api/v1/namespaces/ec-engineering/pods/ec-eng-ci-agent-59dfb68949-n2nh9
  uid: 81586a01-5713-4022-8213-986f9baece51
spec:
  containers:
  - image: enterpriseconnect/agent:v1.1beta
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: agent
    ports:
    - containerPort: 80
      name: http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /
        port: http
        scheme: HTTP
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources: {}
    securityContext: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: ec-eng-ci-agent-token-xtznv
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-242-51-134.ec2.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: ec-eng-ci-agent
  serviceAccountName: ec-eng-ci-agent
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: ec-eng-ci-agent-token-xtznv
    secret:
      defaultMode: 420
      secretName: ec-eng-ci-agent-token-xtznv
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-06-09T13:46:41Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-06-09T13:46:41Z"
    message: 'containers with unready status: [agent]'
    reason: ContainersNotReady
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-06-09T13:46:41Z"
    message: 'containers with unready status: [agent]'
    reason: ContainersNotReady
    status: "False"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-06-09T13:46:41Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://4882945926d3a3860038df8828ca20c25f4de26d69e762c82d9724fd80edf0f3
    image: enterpriseconnect/agent:v1.1beta
    imageID: docker-pullable://enterpriseconnect/agent@sha256:23610d5a50507b7672e63daebfe27386c2b7d26691aab792435254bcee5432a0
    lastState:
      terminated:
        containerID: docker://4882945926d3a3860038df8828ca20c25f4de26d69e762c82d9724fd80edf0f3
        exitCode: 2
        finishedAt: "2020-06-09T16:31:04Z"
        reason: Error
        startedAt: "2020-06-09T16:30:35Z"
    name: agent
    ready: false
    restartCount: 59
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=agent pod=ec-eng-ci-agent-59dfb68949-n2nh9_ec-engineering(81586a01-5713-4022-8213-986f9baece51)
        reason: CrashLoopBackOff
  hostIP: 10.242.51.134
  phase: Running
  podIP: 100.64.3.9
  podIPs:
  - ip: 100.64.3.9
  qosClass: BestEffort
  startTime: "2020-06-09T13:46:41Z"



Logs:

 kubectl logs ec-eng-ci-agent-59dfb68949-n2nh9 -n ec-engineering
 [EC Agent] loading application parameters..
 [EC Daemon x0] 2020/06/09 16:30:10 [scheduling watcher ops..]
 [EC Daemon x0] 2020/06/09 16:30:10 [watcher grpc will listen on :57993]
 [EC Daemon x0] 2020/06/09 16:30:10 [[watcher grpc will listen on :57993]]

**Comment by ayasuda2OO3** [comment]
Thanks @sheshankgujjari. 

From reading the logs, it seems the agent launched without config setting. By default, agent will launched [in watcher mode with daemon enabled](https://github.com/Enterprise-connect/oci/blob/v1.1beta/spec/agent/Dockerfile#L29) if there is no compatible enthronement vars ingested during the deployment. 

Because of this, the [conversion scripts is provided in the instruction](https://github.com/Enterprise-connect/oci/tree/v1.1beta/k8s#agentchart-configuration-conversion) Please follow the steps and generate the necessary setting for the k8 deployment. @simran3695

**Comment by simran3695** [comment]
We have already provided the conf.env file to the deployment. Please let us know any changes or issue in the belwo conf.env file we are passing. Also we have added ocnf.env file in the values.yaml under the "agtConfig: conf.env"

conf.oa2=https://572fef7e-726b-4424-a5ef-a3719a0b0f2f.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
conf.dec=false
conf.dbg=false
conf.app=webui
conf.tid=dSze7G
..
..

**Comment by ayasuda2OO3** [comment]
> We have already provided the conf.env file to the deployment. Please let us know any changes or issue in the belwo conf.env file we are passing. Also we have added ocnf.env file in the values.yaml under the "agtConfig: conf.env"
> 
> conf.oa2=https://572fef7e-726b-4424-a5ef-a3719a0b0f2f.predix-uaa.run.aws-usw02-pr.ice.predix.io/oauth/token
> conf.dec=false
> conf.dbg=false
> conf.app=webui
> conf.tid=dSze7G
> ..
> ..

Whilst I am appreciative for the logs however, I cut off the secrets from your latest post. Trackers' individual discretion is advised for the security. @simran3695 Please reset all relevant client secrets in your previous post for your future usage.

Issue acknowledged. Raising PR in progress. @sheshankgujjari @simran3695

**Comment by ayasuda2OO3** [comment]
The package has been update by #18 please leave feedback for closing. Thank you @sheshankgujjari @simran3695

**Comment by simran3695** [comment]
We will be testing soon and update. Thank you @ayasuda2003

**Comment by simran3695** [comment]
@ayasuda2003 I don't see the changes which is done in "deployment.yaml" in the templates folder 
 for this issue , in the master branch i:e v1.1beta. The changes are seen in V1.1beta_helm_package_update branch. 

And as per my understanding "https://enterprise-connect.github.io/oci/k8s/pkg/agent/charts/agent-0.1.0.tgz" pulls the helm from the master branch i:e v1.1beta. Please confirm on same and let me know if im missed somewhere.

**Comment by ayasuda2OO3** [comment]
> @ayasuda2003 I don't see the changes which is done in "deployment.yaml" in the templates folder
> for this issue , in the master branch i:e v1.1beta. The changes are seen in V1.1beta_helm_package_update branch.
> 
> And as per my understanding "https://enterprise-connect.github.io/oci/k8s/pkg/agent/charts/agent-0.1.0.tgz" pulls the helm from the master branch i:e v1.1beta. Please confirm on same and let me know if im missed somewhere.

Thanks for the inquiry. The branch (v1.1beta_helm_package_update)  is utilised for updating packages, it was henceforth deleted and had been merged to v1.1beta_helm_package, in which it will generate the updated pkg in gh_pages.

v1.1beta is a presentable unified branch serves other purposes, e. g. terraform deployment @ramaraosrikakulapu. For helmchart, the v1.1beta is optionally even with v1.1beta_helm_package.

**Comment by simran3695** [comment]
https://enterprise-connect.github.io/oci/k8s/pkg/agent/charts/agent-0.1.0.tgz. ust for my understanding can you please let me know from which branch this URL will fetch the helm chart ?

**Comment by ayasuda2OO3** [comment]
> https://enterprise-connect.github.io/oci/k8s/pkg/agent/charts/agent-0.1.0.tgz. ust for my understanding can you please let me know from which branch this URL will fetch the helm chart ?

gh_pages @simran3695

**Comment by simran3695** [comment]
@ayasuda2003 We are seeing container failing wih error "unknown agent mode" now

EC Logs :  [EC Agent] 2020/06/17 13:33:37 [cleaned up logging file(s). connectivity.log plugin.log]
 [EC Agent] 2020/06/17 13:33:37 [Rev: v1.1beta.fukuoka.2734]
 [EC Agent] 2020/06/17 13:33:37 [Agent websocket compression is being negotiated at level
0]
 [EC Agent] main pacakge exception: unknown agent mode

Please let us know if we are missing out on something

**Comment by ayasuda2OO3** [comment]
> @ayasuda2003 We are seeing container failing wih error "unknown agent mode" now
> 
> EC Logs : [EC Agent] 2020/06/17 13:33:37 [cleaned up logging file(s). connectivity.log plugin.log]
> [EC Agent] 2020/06/17 13:33:37 [Rev: v1.1beta.fukuoka.2734]
> [EC Agent] 2020/06/17 13:33:37 [Agent websocket compression is being negotiated at level
> 0]
> [EC Agent] main pacakge exception: unknown agent mode
> 
> Please let us know if we are missing out on something

Thanks for the feedback. It seems the agent is not reading the environ variables.Could you share the follow info- (please **hash out any secrets**) @simran3695 

- the running container spec ```kubectl get pods -o yaml```
- the output of the ```printenv``` inside the container.

**Comment by simran3695** [comment]
@ayasuda2003 Please find below the yaml file config. We are not able to login to the pod because the container is not running so we can't provide output of "printenv"


```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/psp: eks.privileged
  creationTimestamp: '2020-06-17T18:39:38Z'
  generateName: ec-eng-ci-agent-655f59b464-
  labels:
    app.kubernetes.io/instance: ec-eng-ci
    app.kubernetes.io/name: agent
    pod-template-hash: 655f59b464
  name: ec-eng-ci-agent-655f59b464-fgfzm
  namespace: ec-engineering
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: ec-eng-ci-agent-655f59b464
      uid: 5709c8d5-8bcb-4a72-88ed-f2e2442fd86d
  resourceVersion: '377866'
  selfLink: /api/v1/namespaces/ec-engineering/pods/ec-eng-ci-agent-655f59b464-fgfzm
  uid: a60b5c28-efae-4738-886c-71f2326289dd
spec:
  containers:
    - command:
        - ./agent
        - '-env'
      image: 'enterpriseconnect/agent:v1.1beta'
      imagePullPolicy: IfNotPresent
      livenessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: http
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      name: agent
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /
          port: http
          scheme: HTTP
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources: {}
      securityContext: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: ec-eng-ci-agent-token-xbtv8
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ip-10-242-51-185.ec2.internal
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: ec-eng-ci-agent
  serviceAccountName: ec-eng-ci-agent
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: ec-eng-ci-agent-token-xbtv8
      secret:
        defaultMode: 420
        secretName: ec-eng-ci-agent-token-xbtv8
status:
  conditions:
    - lastProbeTime: null
      lastTransitionTime: '2020-06-17T18:39:38Z'
      status: 'True'
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: '2020-06-17T18:39:38Z'
      message: 'containers with unready status: [agent]'
      reason: ContainersNotReady
      status: 'False'
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: '2020-06-17T18:39:38Z'
      message: 'containers with unready status: [agent]'
      reason: ContainersNotReady
      status: 'False'
      type: ContainersReady
    - lastProbeTime: null
      lastTransitionTime: '2020-06-17T18:39:38Z'
      status: 'True'
      type: PodScheduled
  containerStatuses:
    - containerID: >-
        docker://4dfac9f83f16cdbfe96fa56a19bbd5618091257c53c096c198a0bca4324301b8
      image: 'enterpriseconnect/agent:v1.1beta'
      imageID: >-
        docker-pullable://enterpriseconnect/agent@sha256:8fee92f671f8ff1d50256b4ba48b061d22e52d9187923413383dddf36190daa3
      lastState:
        terminated:
          containerID: >-
            docker://4dfac9f83f16cdbfe96fa56a19bbd5618091257c53c096c198a0bca4324301b8
          exitCode: 1
          finishedAt: '2020-06-17T18:40:02Z'
          reason: Error
          startedAt: '2020-06-17T18:40:02Z'
      name: agent
      ready: false
      restartCount: 2
      started: false
      state:
        waiting:
          message: >-
            back-off 20s restarting failed container=agent
            pod=ec-eng-ci-agent-655f59b464-fgfzm_ec-engineering(a60b5c28-efae-4738-886c-71f2326289dd)
          reason: CrashLoopBackOff
  hostIP: 10.242.51.185
  phase: Running
  podIP: 100.64.10.188
  podIPs:
    - ip: 100.64.10.188
  qosClass: BestEffort
  startTime: '2020-06-17T18:39:38Z'
```

**Comment by ayasuda2OO3** [comment]
The env var seems rather empty in the spec.. Please ensure to deploy the charts along with the env config.

**Comment by simran3695** [comment]
We have provided the conf.env file while deploying the chart and also the same file we have called in values.yaml under agtconfig object as well.

**Comment by ayasuda2OO3** [comment]
> We have provided the conf.env file while deploying the chart and also the same file we have called in values.yaml under agtconfig object as well.

Issue identified. It seems to be a [known issue in the helm community](https://github.com/helm/helm/issues/1892). The env file which represents the agent setting is not accessible from the package, thus it resulted in the empty list in your chart. We will look for alternatives as a replacement to the env file. Working in Progress. @simran3695 @sheshankgujjari

**Comment by ayasuda2OO3** [comment]
> > We have provided the conf.env file while deploying the chart and also the same file we have called in values.yaml under agtconfig object as well.
> 
> Issue identified. It seems to be a [known issue in the helm community](https://github.com/helm/helm/issues/1892). The env file which represents the agent setting is not accessible from the package, thus it resulted in the empty list in your chart. We will look for alternatives as a replacement to the env file. Working in Progress. 

FYI The issue has been resolved by the PR #20 upon a review. Please find [the spec details in the pkg build log](https://travis-ci.com/github/Enterprise-connect/oci/jobs/351711487#L195).

There is a usage update to the ```helm install```. That is, by adding the flag ```--set-file agtConfig=</path/to/env/file>``` to the command along with the parsing update in the agent chart, it is believed to fix the environment var rendering issue. @simran3695 @sheshankgujjari

**Comment by simran3695** [comment]
@ayasuda2003 we are getting below error while deploying the updated helm chart.

ci/charts/agent/templates/deployment.yaml": template: ec-eng-ci/charts/agent/templates/deployment.yaml:47:41: executing "ec-eng-ci/charts/agent/templates/deployment.yaml" at <.Values.global.agtConfig>: wrong type for value; expected string; got interface {}

**Comment by ayasuda2OO3** [comment]
> @ayasuda2003 we are getting below error while deploying the updated helm chart.
> 
> ci/charts/agent/templates/deployment.yaml": template: ec-eng-ci/charts/agent/templates/deployment.yaml:47:41: executing "ec-eng-ci/charts/agent/templates/deployment.yaml" at <.Values.global.agtConfig>: wrong type for value; expected string; got interface {}

Is the ```--set-file``` in-use? @simran3695 @sheshankgujjari

**Comment by simran3695** [comment]
@ayasuda2003 thankyou for all the help. We are now good to close this issue
