### ISSUE TITLE
Provide a consistent DNS name for EC PODs

### ISSUE THREAD

**Issue by palokam** [EC-Release/oci#26]
**We have to provide a consistent DNS name for EC PODs for TC/any POD to interact with**

**Problem :** As it stands looks like we do not have any SVC attached to the pod, it is difficult and  impossible to know the POD DNS for developer, it is also subjected to change if POD restarts that will break the TC integration or anybody who had the original POD name used for their connectivity... 

**Solution :** We need provide a consist DNS name for EC POD (Client, Server, GW etc), Via K8S Service

**Comment by ayasuda2OO3** [comment]
Proposal acknowledged. PR in progress. @palokam @sheshankgujjari @simran3695

**Comment by ayasuda2OO3** [comment]
The service spec has been added to the agent char in #28 for review. @palokam

**Comment by ayasuda2OO3** [comment]
FYI the [release (v1.0.0-v1.1beta)](https://github.com/Enterprise-connect/oci/releases/tag/v1.0.0-v1.1beta%2B138) is ready for the usage. @palokam @simran3695 @sheshankgujjari please share the feedback for closing. Thanks!

**Comment by ayasuda2OO3** [comment]
Closed solution accepted #33 https://github.com/Enterprise-connect/oci/issues/33#issuecomment-650116070
