### ISSUE TITLE
Enable ingress object in the helm chart for EC Gateway

### ISSUE THREAD

**Issue by sheshankgujjari** [EC-Release/oci#32]
In order to enable EC gateway in kubernetes world, we need to enable ingress object in EC helm chart

Problem : As of today we do not have ingress enabled in EC helm chart, that means we cannot access EC gateway from the internet.

Solution : As we have enabled service for our EC agents, the next step is to have ingress object. By which gateway will be able to access to from outside world.

**Comment by ayasuda2OO3** [comment]
Proposal acknowledged and [tracked in the project](https://github.com/Enterprise-connect/oci/projects/1#card-40739993)

**Comment by simran3695** [comment]
@ayasda2003 Do we have any update on this?

**Comment by ayasuda2OO3** [comment]
PR open #75

**Comment by ayasuda2OO3** [comment]
PR merged #75
