### ISSUE TITLE
Auto Versioning of EC 

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#38]
Right now we have only one option to run EC on EKS i:e v1.1beta with 2734 version. Going forward if we need to use the upgraded version 2737 of v1.1beta or 212 of v1 app version, we would like have an option where we can select our own required version.

**Comment by ayasuda2OO3** [comment]
Proposal accepted. PR in progress.

**Comment by simran3695** [comment]
We are not able to upgrade the EC Version from v1.1beta to v1 212 version. It is failing to deploy continer with below error:
    error: unable to upgrade connection: container not found ("agent")

Please guide us on the same.

**Comment by simran3695** [comment]
This issue is resolved and hence we are closing it. Thanks for your help @ayasda2003
