### ISSUE TITLE
No Connectivity from EC Server (on EKS Cluster) to Gateway (on AWS Corporate/Predix )

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#39]
We are getting below error from EC Server logs which is running on EKS Cluster

EC Server Logs:

/06/26 11:02:58 [health api will be available on the local port#7579]
 [EC Server x0] 2020/06/26 11:02:58 [creating EC_network ..]
 [EC Server x0] 2020/06/26 11:02:59 [initialising super connection for gateway inst#x0]
 [EC Server x0] 2020/06/26 11:02:59 [http proxy was not used for the request: https://corp
-preprod-ecgw2.apps.ge.com/agent]
 [EC Server x0] 2020/06/26 11:02:59 [github.com/wzlib/wzcore.(*Server).admChannelReq.func1
 runtime error: invalid memory address or nil pointer dereference]

We are though able to successfully curl the Corporate gateway, Predix Gateway and UAA from EC Pod on EKS.

**Comment by ayasuda2OO3** [comment]
Would the server be able to establish superconn(s) with the same setting, when outside the k8 cluster?

**Comment by simran3695** [comment]
Yes the same EC server is able to connect and show superconnection when running from outside the k8 cluster, Example is ec-preprod EC Server deployed on the same gateway shows superconnection. We have ran this EC Server on our TC shared/Corporate environment on docker swarm.

**Comment by ayasuda2OO3** [comment]
> Yes the same EC server is able to connect and show superconnection when running from outside the k8 cluster, Example is ec-preprod EC Server deployed on the same gateway shows superconnection. We have ran this EC Server on our TC shared/Corporate environment on docker swarm.

@Gayatri212 @sheshankgujjari @palokam 

As for next step, I will take the following approach to troubleshoot-
1) Test the connectivity in the container. or on the same network/vm.
2) Cross-comparing with the setting.

**Comment by simran3695** [comment]
Just FYI, We are getting below error on the EC Client logs:

[EC Client x0] 2020/06/30 15:17:36 [http proxy was not used for the request: https://digi
tal-preprod-ec-gateway.run.aws-usw02-pr.ice.predix.io/agent]
 [EC Client x0] 2020/06/30 15:17:36 [error while adding the client inst.]
 [EC Client x0] 2020/06/30 15:17:36 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 x509
: certificate signed by unknown authority]

**Comment by ayasuda2OO3** [comment]
> Just FYI, We are getting below error on the EC Client logs:
> 
> [EC Client x0] 2020/06/30 15:17:36 [http proxy was not used for the request: https://digi
> tal-preprod-ec-gateway.run.aws-usw02-pr.ice.predix.io/agent]
> [EC Client x0] 2020/06/30 15:17:36 [error while adding the client inst.]
> [EC Client x0] 2020/06/30 15:17:36 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 x509
> : certificate signed by unknown authority]

FYI the https://digital-preprod-ec-gateway.run.aws-usw02-pr.ice.predix.io/agent does not seem to be a production agent. A beta agent usage is not compatible with agents in production releases. The versioning chart feature is WIP #38

**Comment by simran3695** [comment]
@ayasda2003 We have used the v1.1beta gatewway with version 2734 and did the same test and it is also failing with same error:

[EC Server x0] 2020/07/06 08:55:15 [cleaned up logging file(s). connectivity.log plugin.l
og]
 [EC Server x0] 2020/07/06 08:55:15 [Rev: v1.1beta.fukuoka.2734]
 [EC Server x0] 2020/07/06 08:55:15 [Agent websocket compression is being negotiated at le
vel 0]
 [EC Server x0] 2020/07/06 08:55:15 [refresh duration is specified. Token auto-refresh is
set.]
 [EC Server x0] 2020/07/06 08:55:15 [Fetching new token..]
 [EC Server x0] 2020/07/06 08:55:16 [Token refreshed. The token will be expired in 719 min
utes. Approx. 20 minutes to the next auto-refresh.]
 [EC Server x0] 2020/07/06 08:55:16 [health api will be available on the local port#7579]
 [EC Server x0] 2020/07/06 08:55:16 [creating EC_network ..]
 [EC Server x0] 2020/07/06 08:55:17 [initialising super connection for gateway inst#x0]
 [EC Server x0] 2020/07/06 08:55:17 [http proxy was not used for the request: https://corp
-preprod-ecgw2.apps.ge.com/agent]
 [EC Server x0] 2020/07/06 08:55:17 [github.com/wzlib/wzcore.(*Server).admChannelReq.func1
 runtime error: invalid memory address or nil pointer dereference]

The same has been discussed with Ram and we are expecting issue where Server is not reaching Gateway and we are suspecting network connectivity issue. We have opened an external loadbalancer from our EKS Cluster and will post the results once it is completed.

**Comment by ayasuda2OO3** [comment]
> @ayasda2003 We have used the v1.1beta gatewway with version 2734 and did the same test and it is also failing with same error:
> 
> [EC Server x0] 2020/07/06 08:55:15 [cleaned up logging file(s). connectivity.log plugin.l
> og]
> [EC Server x0] 2020/07/06 08:55:15 [Rev: v1.1beta.fukuoka.2734]
> [EC Server x0] 2020/07/06 08:55:15 [Agent websocket compression is being negotiated at le
> vel 0]
> [EC Server x0] 2020/07/06 08:55:15 [refresh duration is specified. Token auto-refresh is
> set.]
> [EC Server x0] 2020/07/06 08:55:15 [Fetching new token..]
> [EC Server x0] 2020/07/06 08:55:16 [Token refreshed. The token will be expired in 719 min
> utes. Approx. 20 minutes to the next auto-refresh.]
> [EC Server x0] 2020/07/06 08:55:16 [health api will be available on the local port#7579]
> [EC Server x0] 2020/07/06 08:55:16 [creating EC_network ..]
> [EC Server x0] 2020/07/06 08:55:17 [initialising super connection for gateway inst#x0]
> [EC Server x0] 2020/07/06 08:55:17 [http proxy was not used for the request: https://corp
> -preprod-ecgw2.apps.ge.com/agent]
> [EC Server x0] 2020/07/06 08:55:17 [github.com/wzlib/wzcore.(*Server).admChannelReq.func1
> runtime error: invalid memory address or nil pointer dereference]
> 
> The same has been discussed with Ram and we are expecting issue where Server is not reaching Gateway and we are suspecting network connectivity issue. We have opened an external loadbalancer from our EKS Cluster and will post the results once it is completed.

@simran3695  Thank you for the update. We will continue look for any possible workaround  if any.

**Comment by sheshankgujjari** [comment]
@ayasda2003, @ramaraosrikakulapu 

It looks like an issue with Helm packaging not reading the files from environment values from the pod. Based on the test case scenario below that's what our understanding.

Binary version using on EC client and EC server

```
root@tc-eng-ci-thread-connect-0:/tmp# ./agent_linux_sys --ver
 [EC Agent] loading application parameters..
 [EC Agent] 2020/07/06 17:37:47 [v1.1beta.fukuoka.2737]
```

Below are the logs from the EC client running as plain binary in TC pod
```
./agent_linux_sys -mod client -aid 2umYpF -tid 0mygkf -grp ec-server-eks -cid xxx -csc xxx -lpt :7970 -hca :7135 -dur 1200 -hst wss://corp-preprod-ecgw2.apps.ge.com/agent -oa2 https://90100c29-e183-4ca1-bfc6-d10959add5c3.predix-uaa.run.aws-usw02-dev.ice.predix.io/oauth/token
 [EC Agent] loading application parameters..
[
           ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
          ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
          ▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀▀▀
          ▐░▌          ▐░▌   
          ▐░█▄▄▄▄▄▄▄▄▄ ▐░▌
          ▐░░░░░░░░░░░▌▐░▌
          ▐░█▀▀▀▀▀▀▀▀▀ ▐░▌
          ▐░▌          ▐░▌
          ▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄▄▄ 
          ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
           ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀  @Digital Connect 
]
 [EC Client x0] 2020/07/06 17:14:42 [cleaned up logging file(s). connectivity.log plugin.log]
 [EC Client x0] 2020/07/06 17:14:42 [Rev: v1.1beta.fukuoka.2737]
 [EC Client x0] 2020/07/06 17:14:42 [Agent websocket compression is being negotiated at level 0]
 [EC Client x0] 2020/07/06 17:14:42 [refresh duration is specified. Token auto-refresh is set.]
 [EC Client x0] 2020/07/06 17:14:42 [Fetching new token..]
 [EC Client x0] 2020/07/06 17:14:42 [Token refreshed. The token will be expired in 719 minutes. Approx. 20 minutes to the next auto-refresh.]
 [EC Client x0] 2020/07/06 17:14:42 [health api will be available on the local port#:7135]
 [EC Client x0] 2020/07/06 17:14:42 [[VLAN] client is listening on port# :7970]
 [EC Client x0] 2020/07/06 17:14:42 [creating EC_Network ..]
 [EC Client x0] 2020/07/06 17:14:58 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Client x0] 2020/07/06 17:14:59 [error while adding the client inst.]
 [EC Client x0] 2020/07/06 17:14:59 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
 [EC Client x0] 2020/07/06 17:16:29 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Client x0] 2020/07/06 17:16:30 [error while adding the client inst.]
 [EC Client x0] 2020/07/06 17:16:30 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
 [EC Client x0] 2020/07/06 17:16:41 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Client x0] 2020/07/06 17:16:41 [error while adding the client inst.]
 [EC Client x0] 2020/07/06 17:16:41 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
 [EC Client x0] 2020/07/06 17:31:36 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Client x0] 2020/07/06 17:31:37 [error while adding the client inst.]
 [EC Client x0] 2020/07/06 17:31:37 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
 [EC Client x0] 2020/07/06 17:33:57 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Client x0] 2020/07/06 17:33:58 [client#2umYpF connection is pending for a confirmation from the gateway]
 [EC Client x0] 2020/07/06 17:33:58 [connection request has been received by the gateway with the bindId#fCy5dUYvEe]
 [EC Client x0] 2020/07/06 17:34:10 [agent exiting TCP_REQUEST.]
 [EC Client x0] 2020/07/06 17:34:10 [bind#: fCy5dUYvEe has been removed from the pool.]
 [EC Client x0] 2020/07/06 17:34:42 [Triggering token Auto-Refresh..]
 [EC Client x0] 2020/07/06 17:34:43 [Token refreshed. The token will be expired in 719 minutes. Approx. 20 minutes to the next auto-refresh.]
```

Below are the logs from the EC server running as plain binary in one EC2 machine

```
[EC Server x0] 2020/07/06 17:33:30 [cleaned up logging file(s). connectivity.log plugin.log]
 [EC Server x0] 2020/07/06 17:33:30 [Rev: v1.1beta.fukuoka.2734]
 [EC Server x0] 2020/07/06 17:33:30 [Agent websocket compression is being negotiated at level 0]
 [EC Server x0] 2020/07/06 17:33:30 [refresh duration is specified. Token auto-refresh is set.]
 [EC Server x0] 2020/07/06 17:33:30 [Fetching new token..]
 [EC Server x0] 2020/07/06 17:33:30 [Token refreshed. The token will be expired in 719 minutes. Approx. 20 minutes to the next auto-refresh.]
 [EC Server x0] 2020/07/06 17:33:30 [health api will be available on the local port#1199]
 [EC Server x0] 2020/07/06 17:33:30 [creating EC_network ..]
 [EC Server x0] 2020/07/06 17:33:31 [initialising super connection for gateway inst#x0]
 [EC Server x0] 2020/07/06 17:33:31 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Server x0] 2020/07/06 17:33:32 [super connection established for gateway inst#x0]
 [EC Server x0] 2020/07/06 17:33:58 [client#2umYpF requests connection with the bind id#fCy5dUYvEe.]
 [EC Server x0] 2020/07/06 17:33:58 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
 [EC Server x0] 2020/07/06 17:33:59 [server has been successfully created for clientId#2umYpF with bindId#fCy5dUYvEe]
 [EC Server x0] 2020/07/06 17:33:59 [gateway connection{host=wss://corp-preprod-ecgw2.apps.ge.com/agent, session=1O16UWOxil,gatewayId=02:62:da:d4:d5:83} established for client# 2umYpF with bindId#fCy5dUYvEe, to VLAN address: 127.0.0.1:7970 if -vln is enabled.]
 [EC Server x0] 2020/07/06 17:33:59 [websocket is found in the pool for clientId#2umYpF]
```

**Comment by ayasuda2OO3** [comment]
> @ayasda2003, @ramaraosrikakulapu
> 
> It looks like an issue with Helm packaging not reading the files from environment values from the pod. Based on the test case scenario below that's what our understanding.
> 
> Binary version using on EC client and EC server
> 
> ```
> root@tc-eng-ci-thread-connect-0:/tmp# ./agent_linux_sys --ver
>  [EC Agent] loading application parameters..
>  [EC Agent] 2020/07/06 17:37:47 [v1.1beta.fukuoka.2737]
> ```
> 
> Below are the logs from the EC client running as plain binary in TC pod
> 
> ```
> ./agent_linux_sys -mod client -aid 2umYpF -tid 0mygkf -grp ec-server-eks -cid xxx -csc xxx -lpt :7970 -hca :7135 -dur 1200 -hst wss://corp-preprod-ecgw2.apps.ge.com/agent -oa2 https://90100c29-e183-4ca1-bfc6-d10959add5c3.predix-uaa.run.aws-usw02-dev.ice.predix.io/oauth/token
>  [EC Agent] loading application parameters..
> [
>            ▄▄▄▄▄▄▄▄▄▄▄  ▄▄▄▄▄▄▄▄▄▄▄
>           ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
>           ▐░█▀▀▀▀▀▀▀▀▀ ▐░█▀▀▀▀▀▀▀▀▀
>           ▐░▌          ▐░▌   
>           ▐░█▄▄▄▄▄▄▄▄▄ ▐░▌
>           ▐░░░░░░░░░░░▌▐░▌
>           ▐░█▀▀▀▀▀▀▀▀▀ ▐░▌
>           ▐░▌          ▐░▌
>           ▐░█▄▄▄▄▄▄▄▄▄ ▐░█▄▄▄▄▄▄▄▄▄ 
>           ▐░░░░░░░░░░░▌▐░░░░░░░░░░░▌
>            ▀▀▀▀▀▀▀▀▀▀▀  ▀▀▀▀▀▀▀▀▀▀▀  @Digital Connect 
> ]
>  [EC Client x0] 2020/07/06 17:14:42 [cleaned up logging file(s). connectivity.log plugin.log]
>  [EC Client x0] 2020/07/06 17:14:42 [Rev: v1.1beta.fukuoka.2737]
>  [EC Client x0] 2020/07/06 17:14:42 [Agent websocket compression is being negotiated at level 0]
>  [EC Client x0] 2020/07/06 17:14:42 [refresh duration is specified. Token auto-refresh is set.]
>  [EC Client x0] 2020/07/06 17:14:42 [Fetching new token..]
>  [EC Client x0] 2020/07/06 17:14:42 [Token refreshed. The token will be expired in 719 minutes. Approx. 20 minutes to the next auto-refresh.]
>  [EC Client x0] 2020/07/06 17:14:42 [health api will be available on the local port#:7135]
>  [EC Client x0] 2020/07/06 17:14:42 [[VLAN] client is listening on port# :7970]
>  [EC Client x0] 2020/07/06 17:14:42 [creating EC_Network ..]
>  [EC Client x0] 2020/07/06 17:14:58 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Client x0] 2020/07/06 17:14:59 [error while adding the client inst.]
>  [EC Client x0] 2020/07/06 17:14:59 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
>  [EC Client x0] 2020/07/06 17:16:29 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Client x0] 2020/07/06 17:16:30 [error while adding the client inst.]
>  [EC Client x0] 2020/07/06 17:16:30 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
>  [EC Client x0] 2020/07/06 17:16:41 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Client x0] 2020/07/06 17:16:41 [error while adding the client inst.]
>  [EC Client x0] 2020/07/06 17:16:41 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
>  [EC Client x0] 2020/07/06 17:31:36 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Client x0] 2020/07/06 17:31:37 [error while adding the client inst.]
>  [EC Client x0] 2020/07/06 17:31:37 [github.com/wzlib/wzcore.(*Client).Hire.func6.2.1 websocket: bad handshake]
>  [EC Client x0] 2020/07/06 17:33:57 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Client x0] 2020/07/06 17:33:58 [client#2umYpF connection is pending for a confirmation from the gateway]
>  [EC Client x0] 2020/07/06 17:33:58 [connection request has been received by the gateway with the bindId#fCy5dUYvEe]
>  [EC Client x0] 2020/07/06 17:34:10 [agent exiting TCP_REQUEST.]
>  [EC Client x0] 2020/07/06 17:34:10 [bind#: fCy5dUYvEe has been removed from the pool.]
>  [EC Client x0] 2020/07/06 17:34:42 [Triggering token Auto-Refresh..]
>  [EC Client x0] 2020/07/06 17:34:43 [Token refreshed. The token will be expired in 719 minutes. Approx. 20 minutes to the next auto-refresh.]
> ```
> 
> Below are the logs from the EC server running as plain binary in one EC2 machine
> 
> ```
> [EC Server x0] 2020/07/06 17:33:30 [cleaned up logging file(s). connectivity.log plugin.log]
>  [EC Server x0] 2020/07/06 17:33:30 [Rev: v1.1beta.fukuoka.2734]
>  [EC Server x0] 2020/07/06 17:33:30 [Agent websocket compression is being negotiated at level 0]
>  [EC Server x0] 2020/07/06 17:33:30 [refresh duration is specified. Token auto-refresh is set.]
>  [EC Server x0] 2020/07/06 17:33:30 [Fetching new token..]
>  [EC Server x0] 2020/07/06 17:33:30 [Token refreshed. The token will be expired in 719 minutes. Approx. 20 minutes to the next auto-refresh.]
>  [EC Server x0] 2020/07/06 17:33:30 [health api will be available on the local port#1199]
>  [EC Server x0] 2020/07/06 17:33:30 [creating EC_network ..]
>  [EC Server x0] 2020/07/06 17:33:31 [initialising super connection for gateway inst#x0]
>  [EC Server x0] 2020/07/06 17:33:31 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Server x0] 2020/07/06 17:33:32 [super connection established for gateway inst#x0]
>  [EC Server x0] 2020/07/06 17:33:58 [client#2umYpF requests connection with the bind id#fCy5dUYvEe.]
>  [EC Server x0] 2020/07/06 17:33:58 [http proxy was not used for the request: https://corp-preprod-ecgw2.apps.ge.com/agent]
>  [EC Server x0] 2020/07/06 17:33:59 [server has been successfully created for clientId#2umYpF with bindId#fCy5dUYvEe]
>  [EC Server x0] 2020/07/06 17:33:59 [gateway connection{host=wss://corp-preprod-ecgw2.apps.ge.com/agent, session=1O16UWOxil,gatewayId=02:62:da:d4:d5:83} established for client# 2umYpF with bindId#fCy5dUYvEe, to VLAN address: 127.0.0.1:7970 if -vln is enabled.]
>  [EC Server x0] 2020/07/06 17:33:59 [websocket is found in the pool for clientId#2umYpF]
> ```

Thanks for the effort @sheshankgujjari , we are working with @simran3695 to identify the root cause, there might exist an issue relevant to the tls cert recognition @agent. Will keep everyone posted. @palokam @ramaraosrikakulapu

**Comment by ayasuda2OO3** [comment]
Issue identified. The linux distribution[1] does not contain the cert-chain used in TLS handshake with the LBer. Whilst busybox maintains the overall small footprint by omitting the ca-certificates[2] pkg, linux Alpine might be a good alternative. PR in progress. @sheshankgujjari @simran3695 @ramaraosrikakulapu @palokam 


Reference:
[1] current [linux distribution](https://github.com/Enterprise-connect/oci/blob/v1.1beta_helm_pkg/spec/agent/Dockerfile#L13)
[2] linux alpine [ca-certificates spec](https://git.alpinelinux.org/ca-certificates/)

**Comment by simran3695** [comment]
This issue has now been resolved, hence we are closing it. Thankyou for all the help @ayasda2003
