### ISSUE TITLE
Gateway load balancing - Terraform scripts for auto deployment

### ISSUE THREAD

**Issue by ramaraosrikakulapu** [EC-Release/oci#6]
Create terraform scripts for - 

- Provisioning the 2 VM's for deploying gateway load balancer and watcher
- Deploy load balancer in a VM
- Deploy watcher in other VM

**Comment by ramaraosrikakulapu** [comment]
Started working on preparing initial scripts and requested for EC2 Create and Delete access on AWS environment to test the scripts.

**Comment by ramaraosrikakulapu** [comment]
Checked in the initial scripts

**Comment by ramaraosrikakulapu** [comment]
Completed so far - 
- Started with AWS
- Able to create EC2 instances
- Install packages
- Read values from external tfvars file

Stuck at couple of issues and working on - 
- Copy watcher configuration file to gateway EC2 and start watcher
- Update environment.env with watcher hosts and copy file to lber EC2

**Comment by ramaraosrikakulapu** [comment]
Trying with file provisioner and remote-exec to copy files into EC2 but it required SSH permission which is not allowed in current AWS sandbox VPC. Got a suggestion from Zameer to use API's to copy files. Have to learn and try the option.

**Comment by ayasuda2OO3** [comment]
> Trying with file provisioner and remote-exec to copy files into EC2 but it required SSH permission which is not allowed in current AWS sandbox VPC. Got a suggestion from Zameer to use API's to copy files. Have to learn and try the option.

Does not sound right.. 
- check out [how to run remote-exec](https://www.terraform.io/docs/provisioners/remote-exec.html)
-  example [how to run a remote script here](https://github.com/Enterprise-connect/oci/tree/v1.1beta/k8s#agentchart-configuration-conversion)

@ramaraosrikakulapu please help tag Zameer as a contributor upon this subject if possible. @palokam

**Comment by ramaraosrikakulapu** [comment]
Thanks @ayasuda2003 

I already tried the option for remote-exec, but in built it work with ssh or winrm and need to provide connection settings. Unfortunately, we have env, which not allowing ssh(or winrm) connections to EC2.

And as shown the example, I am also downloading the agent, but problem is to copy conf.yml file to run the agent.

One solution I am planning to have S3 bucket and upload the conf files to S3 and then download to EC2 instances and run the agents.

**Comment by ayasuda2OO3** [comment]
I would try to make the example leaner for adoption by avoiding using ***add-ons***. What does the user_data look like? assuming you are using aws as the "provider". your resource should be similar as follows-
```
resource "aws_instance" "my-instance" {
	ami = "ami-04169656fea786776"
	instance_type = "t2.nano"
	key_name = "${aws_key_pair.terraform-demo.key_name}"
	user_data = << EOF
		#! /bin/bash
                sudo apt-get update
		sudo systemctl enable apache2
		echo "<h1>Deployed via Terraform</h1>" | sudo tee /var/www/html/index.html
                export EC_CSC={your-passphrase}; bash < execute-the-remote-script.sh #see example
	EOF
	tags = {
		Name = "Terraform"	
		Batch = "5AM"
	}
}
```

Secondly, when execute a remote bash ```execute-the-remote-script.sh``` in above example), things we can do in the script as follows-

```bash
#usr/bin/bash
wget <the url of an agent bin> && tar xvf
wget <the url of the conf.yaml.asc>
#passphrase passed on via Env Var $EC_CSC
./agent -dec conf.yaml.asc
```

***Reference:***
https://www.bogotobogo.com/DevOps/Terraform/Terraform-terraform-userdata.php

**Comment by ramaraosrikakulapu** [comment]
Right.. I am doing the same way and [here](https://github.com/Enterprise-connect/oci/blob/4448c530e68c92ad030eb8ebc7aa66b8b904f022/spec/loadbalancer/terraform/main.tf#L40) is my user_data section for a gateway VM.

Either we can pass set of commands or we can group all commands in a script file and execute it in vm resource. Since we have little bit bigger set of actions to do, I put every thing in a file and passing it to user_data section. Unfortunately, they are just commands to execute and believe not possible to pass files from host system.

And I like the approach of using of ```bash``` instead of having a big command 👍

**Comment by ayasuda2OO3** [comment]
> Right.. I am doing the same way and [here](https://github.com/Enterprise-connect/oci/blob/4448c530e68c92ad030eb8ebc7aa66b8b904f022/spec/loadbalancer/terraform/main.tf#L40) is my user_data section for a gateway VM.

I think we are not on the same page.. where is the **remote script** to download the files? I don't understand the **not possible** part of this subject.

**Comment by ramaraosrikakulapu** [comment]
Hi @ayasuda2003 .. As per our call, I will try with configuration template and replace functions. Thank you for the valuable suggestion.

**Comment by ramaraosrikakulapu** [comment]
Able to create the watcher's config.yml in EC2 and sending the values dynamically at run time. However, watcher is not starting and giving the following error - 
```
[github.com/Enterprise-Connect/agent/watcher.(*Watcher).Scale.func1 Error response from daemon: Pool overlaps with otherone on this address space]
```
and looking into it.

**Comment by ramaraosrikakulapu** [comment]
Updating with current state - 

- Able to create EC2 instances in AWS VPC (Using AWS sandbox VPC for testing purposes)
- For now, have to start watcher manually in Watcher VM's due to the [issue](https://github.com/Enterprise-connect/oci/issues/6#issuecomment-637072876). @ayasuda2003 is helping to solve the problem
- Gateway load balancer is running fine and reading the watcher IP addresses dynamically from watcher VM configuration script
- Documentation is in progress
