### ISSUE TITLE
EC Agent deploying only 1 pod even when HA enabled (replica count = 2)

### ISSUE THREAD

**Issue by simran3695** [EC-Release/oci#63]
When we have increased the replica countof the agent to 2, it is still deploying only 1 agent instance/pod. The replica count increment when checked in the agent spec goes to the "max replica count" instead of the "desired replica count" parameter.
====================EC Client Spec=========================

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '1'

Please help us understand and resolve this.

**Comment by ayasuda2OO3** [comment]
Acknowledged. PR in progress. @simran3695 @sheshankgujjari

**Comment by ryan-howell** [comment]
@simran3695 can you please provide the following for this Issue:
- What are you trying to accomplish?
- What did you try to do (exact steps taken)?
- What did you expect to happen?
- What actually happened?
- *Provide as much detail as possible such as relevant logs or cli output.*

**Comment by simran3695** [comment]
This issue is resolved now.
