### ISSUE TITLE
Repo Needs Issue/PR Templates

### ISSUE THREAD

**Issue by ryan-howell** [EC-Release/oci#64]
To ensure a consistent and meaningful interaction with the development community, this repo should have pre-defined Issue and PR templates so the correct info can be provided when interacting with the development team for Issues and Code Contributions. This repo should have the following (at minimum):

Issue Templates:
- Feature Requests
- Bug Reports

PR Templates:
- Pull Request Template

Some great examples and additional info on PR/Issue Templates:
https://github.com/devspace/awesome-github-templates
https://github.com/stevemao/github-issue-templates
https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository

**Comment by ayasuda2OO3** [comment]
@ryan-howell thanks for the suggestion. Please contribute as you suggested. Will encourage but not regulate.
