### ISSUE TITLE
EKS EC Clients are not working 

### ISSUE THREAD

**Issue by AakritiTalwar12** [EC-Release/oci#72]
Hi Team,

We are using 0.1.3 helm version for EC EKS client agents. They were working completely fine up till now but since the restart of the agents we are getting the attached error and all the client agents are failing , we are not facing the same issue with server agents.
We can see the client.yaml has been changed with some proxy parameter addition, that might be causing the issue.
Request you to please look into it.

![image](https://user-images.githubusercontent.com/58229454/88856208-b6b7d780-d211-11ea-960f-06fdb49459f5.png)

![image](https://user-images.githubusercontent.com/58229454/88856403-0bf3e900-d212-11ea-854a-0115a1c07181.png)

**Comment by ayasuda2OO3** [comment]
Thanks for the information. There was a [spec PR that makes the proxy setting mandatory](https://github.com/Enterprise-connect/oci/pull/71) earlier. This may have been the issue with the [config setting](https://github.com/Enterprise-connect/oci/blob/v1_oci_spec/spec/agent/agent.sh#L28) 

Do you have a ```conf.pxy=""``` in the chart ```variable.yaml```?

**Comment by AakritiTalwar12** [comment]
no the values.yml contains

conf.pxy=false

**Comment by ayasuda2OO3** [comment]
> no the values.yml contains
> 
> conf.pxy=false

Thanks that makes sense. The field ```conf.pxy``` currently accepts only string value. By update it to ```conf.pxy=""``` may fix the issue. @ramaraosrikakulapu @AakritiTalwar12

**Comment by ayasuda2OO3** [comment]
Thanks for the #73 @ramaraosrikakulapu 

@AakritiTalwar12 please share feedback if this is a good fix. Thanks again!

**Comment by simran3695** [comment]
@ayasuda2OO3 After the revert changes we tried deploying app with proxy flag as "false", somehow all EC were failing with connection refused dail tcp error and containers livess and readiness check were also failing and container were restarting. I tried removing the conf.pxy flag from the agent values.yaml and everything is up and running now. 

Can you please validate the proxy flag once?

**Comment by ayasuda2OO3** [comment]
> @ayasuda2OO3 After the revert changes we tried deploying app with proxy flag as "false", somehow all EC were failing with connection refused dail tcp error and containers livess and readiness check were also failing and container were restarting. I tried removing the conf.pxy flag from the agent values.yaml and everything is up and running now.
> 
> Can you please validate the proxy flag once?

@simran3695 as suggested, the ```conf.pxy=false``` is now working as expected (see [build log](https://travis-ci.com/github/Enterprise-connect/oci/builds/177915965#L510)). Upon deploy, the agent setting will be switched on/off the line ```pxy: <proxy>``` in the container based on the values.yaml. Please review #74 for merge. Thanks!

**Comment by simran3695** [comment]
Proxy flag is working as fine. Hence, closing this issue.
