### ISSUE TITLE
ECs failing due to main pacakge exception: flag: vln has unexpected value

### ISSUE THREAD

**Issue by AakritiTalwar12** [EC-Release/oci#97]
Hi ,

I am trying to deploy an EC client agent on EKS Cluster which is giving me the below error:

[EC Agent] main pacakge exception: flag:vln has unexpected value:v:type: map[interface {}]interface {}

This EC does not require any TLS or VLAN plugin.
Also when I tried Synching the already working EC clients all of them are failing.
I am using only agent and agent+helper binaries for these ECs.
I request you to please look into this issue for a solution that requires minimum changes to the existing ECs if possible since each change in the helm has to be added to a list of about 50 ECs.
<img width="563" alt="error" src="https://user-images.githubusercontent.com/58229454/94586122-7d95f500-029e-11eb-8975-d2be97e1ead9.PNG">
<img width="481" alt="requirements" src="https://user-images.githubusercontent.com/58229454/94586368-c352bd80-029e-11eb-8a56-aa539d2cc9d8.PNG">

@simran3695 @sheshankgujjari

Thanks,
Aakriti

**Comment by palokam** [comment]
@AakritiTalwar12  - can you assign this to @ayasuda2OO3? @simran can you be able  to help?

@ayasuda2OO3, do you need more details on this error?

**Comment by simran3695** [comment]
@palokam The issue has been acknowledged by Chia and I have connected with him over the call and it has now been resolved. The same as been validated too. Also I have informed Aakriti of the required changes, we should be good now.

**Comment by palokam** [comment]
Thanks @simran3695 @ayasuda2OO3

**Comment by simran3695** [comment]
We are closing this issue as it has been resolved.
Thankyou for your help @ayasuda2OO3
